#!/usr/bin/env python3
from __future__ import annotations

import argparse
import shutil
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from paperlib import (
    atomic_write_text,
    dump_yaml,
    load_yaml,
    resolve_repo,
    slugify,
    validate_paper_dir,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the global paper index and collections.")
    parser.add_argument("--repo", help="Paper Reader repository root; defaults to cwd")
    return parser.parse_args()


def paper_record(repo: Path, paper_dir: Path, metadata: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": metadata["id"],
        "title": metadata["title"],
        "title_zh": metadata.get("title_zh", ""),
        "authors": metadata.get("authors", []),
        "year": metadata["year"],
        "venue": metadata.get("publication", {}).get("venue", ""),
        "identifiers": metadata.get("identifiers", {}),
        "domains": metadata.get("research", {}).get("domains", []),
        "topics": metadata.get("research", {}).get("topics", []),
        "task": metadata.get("research", {}).get("task", ""),
        "method_family": metadata.get("research", {}).get("method_family", ""),
        "status": metadata.get("workflow", {}).get("status", ""),
        "code_url": metadata.get("artifacts", {}).get("code_url", ""),
        "path": paper_dir.relative_to(repo).as_posix(),
    }


def collection_page(tag: str, records: list[dict[str, Any]]) -> str:
    lines = [
        "<!-- Generated by build_index.py. Do not edit manually. -->",
        "",
        f"# {tag}",
        "",
    ]
    for record in sorted(records, key=lambda item: (-item["year"], item["id"])):
        label = record["title_zh"] or record["title"]
        notes_path = f"../../{record['path']}/notes.md"
        venue = f" · {record['venue']}" if record["venue"] else ""
        lines.append(f"- [{label}]({notes_path}) — {record['year']}{venue}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    repo = resolve_repo(args.repo)
    papers_root = repo / "papers"
    records: list[dict[str, Any]] = []
    failures: list[str] = []

    for paper_dir in sorted(path for path in papers_root.iterdir() if path.is_dir()):
        issues = validate_paper_dir(paper_dir, strict=True)
        if issues:
            failures.append(f"{paper_dir.name}: " + "; ".join(issues))
            continue
        metadata = load_yaml(paper_dir / "metadata.yaml")
        if metadata.get("workflow", {}).get("status") not in {"verified", "synthesized"}:
            failures.append(f"{paper_dir.name}: canonical paper is not verified")
            continue
        records.append(paper_record(repo, paper_dir, metadata))

    if failures:
        print("Index generation stopped because canonical papers are invalid:")
        for failure in failures:
            print(f"- {failure}")
        return 1

    records.sort(key=lambda item: (-item["year"], item["id"]))
    index = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "paper_count": len(records),
        "papers": records,
    }
    dump_yaml(repo / "index.yaml", index)

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    display_names: dict[str, str] = {}
    for record in records:
        for tag in [*record["domains"], *record["topics"]]:
            if not str(tag).strip():
                continue
            key = slugify(str(tag))
            grouped[key].append(record)
            display_names.setdefault(key, str(tag))

    generated_dir = repo / "collections" / "generated"
    if generated_dir.exists():
        shutil.rmtree(generated_dir)
    generated_dir.mkdir(parents=True)

    index_lines = [
        "<!-- Generated by build_index.py. Do not edit manually. -->",
        "",
        "# Generated collections",
        "",
    ]
    for key in sorted(grouped):
        filename = f"{key}.md"
        atomic_write_text(
            generated_dir / filename,
            collection_page(display_names[key], grouped[key]),
        )
        index_lines.append(
            f"- [{display_names[key]}]({filename}) — {len(grouped[key])} papers"
        )
    if not grouped:
        index_lines.append("- No tagged papers yet.")
    index_lines.append("")
    atomic_write_text(generated_dir / "_index.md", "\n".join(index_lines))

    print(f"Indexed {len(records)} papers.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

